// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYH6Lr5BT6fOpoYYcm0ytfm0a2Xwta7_g',
    appId: '1:998364214913:web:6305252f205d9831b37f80',
    messagingSenderId: '998364214913',
    projectId: 'adv-exam-fb',
    authDomain: 'adv-exam-fb.firebaseapp.com',
    storageBucket: 'adv-exam-fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoHZDo8Rkd1qQ87GR4B7kxZG4Fqybiq7M',
    appId: '1:998364214913:android:d415bebe0b216fbab37f80',
    messagingSenderId: '998364214913',
    projectId: 'adv-exam-fb',
    storageBucket: 'adv-exam-fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEe27WAqN5j0nsqrVZjm8oIqBPySHPPnI',
    appId: '1:998364214913:ios:9e7b9fbb4022edd3b37f80',
    messagingSenderId: '998364214913',
    projectId: 'adv-exam-fb',
    storageBucket: 'adv-exam-fb.firebasestorage.app',
    iosBundleId: 'com.example.advExam2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEe27WAqN5j0nsqrVZjm8oIqBPySHPPnI',
    appId: '1:998364214913:ios:9e7b9fbb4022edd3b37f80',
    messagingSenderId: '998364214913',
    projectId: 'adv-exam-fb',
    storageBucket: 'adv-exam-fb.firebasestorage.app',
    iosBundleId: 'com.example.advExam2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYH6Lr5BT6fOpoYYcm0ytfm0a2Xwta7_g',
    appId: '1:998364214913:web:921a19fe709e054bb37f80',
    messagingSenderId: '998364214913',
    projectId: 'adv-exam-fb',
    authDomain: 'adv-exam-fb.firebaseapp.com',
    storageBucket: 'adv-exam-fb.firebasestorage.app',
  );
}
